In [1]:
import json

In [4]:
correct = []
format_correct_answer_wrong = []
format_wrong_answer_correct = []
format_wrong_answer_wrong = []
with open("baseline_result.jsonl") as f:
    for line in f:
        line = json.loads(line)
        if line["format_reward"] == 1 and line["answer_reward"] == 1:
            correct.append(line)
        elif line["format_reward"] == 0 and line["answer_reward"] == 1:
            format_wrong_answer_correct.append(line)
        elif line["format_reward"] == 1 and line["answer_reward"] == 0:
            format_correct_answer_wrong.append(line)
        else:
            format_wrong_answer_wrong.append(line)
        

In [5]:
print(len(correct))
print(len(format_correct_answer_wrong))
print(len(format_wrong_answer_correct))
print(len(format_wrong_answer_wrong))

215
1226
0
6032


In [87]:
correct_dict_list = []
for i in correct:
    correct_dict = {}
    correct_dict["prompt"] = i["prompt"]
    correct_dict["response"] = i["response"]
    correct_dict_list.append(correct_dict)

with open("/home/aiscuser/repos/assignment5-alignment/data/gsm8k/train_correct.jsonl", "w") as f:
    for i in correct_dict_list:
        json.dump(i, f)
        f.write("\n")

In [99]:
correct_prompt = set()

In [100]:
with open("/home/aiscuser/repos/assignment5-alignment/data/gsm8k/train_correct.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        line = json.loads(line.strip())
        prompt = line["prompt"]
        correct_prompt.add(prompt)

In [102]:
correct = []
with open("/home/aiscuser/repos/assignment5-alignment/data/gsm8k/processed_train.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        line = json.loads(line.strip())
        if line["prompt"] in correct_prompt:
            correct_dict = {}
            correct_dict["prompt"] = line["prompt"]
            correct_dict["response"] = line["response"]
            correct.append(correct_dict)
with open("/home/aiscuser/repos/assignment5-alignment/data/gsm8k/correct.jsonl", "w") as f:
    for i in correct:
        json.dump(i, f)
        f.write("\n")

In [2]:
import json

In [3]:
processed_train = []
with open("/home/aiscuser/repos/assignment5-alignment/cs336_alignment/prompts/r1_zero.prompt", "r") as file:
    prompt = file.read()
with open("/home/aiscuser/repos/assignment5-alignment/data/gsm8k/train.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        train_sample = {}
        line = json.loads(line)
        train_sample["prompt"] = prompt.format(question = line["question"])
        train_sample["response"] = line["answer"].replace("\n####", " </think> <answer>") + " </answer>"
        processed_train.append(train_sample)

with open("/home/aiscuser/repos/assignment5-alignment/data/gsm8k/processed_train.jsonl", "w") as f:
    for i in processed_train:
        json.dump(i, f)
        f.write("\n")

    
        


In [83]:
def a(b:str, x:int):
    return b+x

In [84]:
a(5,10)

15

In [68]:
def extract_answer(passage: str) -> str:
    if "\\boxed" in passage:
        return extract_boxed_answer(passage)
    return None

In [72]:
for i in format_wrong_answer_wrong[:10]:
    print (f"-----------question--------")
    print (f"response: {i["response"]}")
    print ("--------")
    print (f"answer: {i["answer"]}")
    print ("-----------done-------------")
    

-----------question--------
response: We know that Natalia sold clips in April and May, and we are asked to find out how many clips she sold altogether. First, let's look at the information given. In April, she sold clips to 48 friends, and she sold half as many clips in May. Let's call the number of clips she sold in April C. Therefore, the number of clips she sold in May is one half the number of clips she sold in April, which we can denote as C/2. We are asked to find out C + C/2, which is the same as 3/2C. According to the problem, 3/2C = 48. Let's now solve 3/2C = 48 for C. Multiply both sides of the equation by 2, so you get 3C = 96. Finally, divide both sides of the new equation by 3, and you get C = 32. This means that Natalia sold clips to 32 friends in April, and half that number, which is 16, in May. Now, we can do 32 + 16 to see how many clips Natalia sold altogether. 32 + 16 = 48</answer>
--------
answer: Natalia sold 48/2 = <<48/2=24>>24 clips in May.
Natalia sold 48+24 =

In [32]:
import torch

In [44]:
x = torch.randn(3,2)

In [36]:
x

tensor([ 0.7861,  0.1274, -0.4862])

In [40]:
y = torch.randn(4)

In [41]:
torch.cat([x,y], dim=0)

tensor([ 0.7861,  0.1274, -0.4862, -0.8975,  0.8254,  1.5767, -0.5882])

In [45]:
torch.sum(x, dim=-1)

tensor([ 1.3606,  0.4101, -0.7881])

In [46]:
torch.sum(x, dim=-1, keepdim=True)

tensor([[ 1.3606],
        [ 0.4101],
        [-0.7881]])

In [47]:
response = "In a 90-minute soccer game, Mark played for a total of 20 + 35 = 55 minutes. Since the game lasts for 90 minutes, the time he was on the sideline is 90 - 55 = 35 minutes. </think> <answer> 35 minutes </answer>"

In [ ]:
with open ("")

In [48]:
if "</think> <answer>" in response and "</answer>" in response:
    model_answer = response.split("<answer>")[-1].replace("</answer>", "")

In [49]:
model_answer

' 35 minutes '

In [50]:
answer = "Mark played for a total of 20 + 35 = <<20+35=55>>55 minutes.\nSo, he was on the sideline for 90 - 55 = <<90-55=35>>35 minutes.\n#### 35"

In [53]:
import re

In [54]:
def mathd_normalize_answer(answer):
    if answer is None:
        return None
    answer = answer.strip()
    try:
        # Remove enclosing `\text{}`.
        m = re.search("^\\\\text\{(?P<text>.+?)\}$", answer)
        if m is not None:
            answer = m.group("text").strip()
        return _strip_string(answer)
    except:
        return answer

<>:7: SyntaxWarning: invalid escape sequence '\{'
<>:7: SyntaxWarning: invalid escape sequence '\{'
/tmp/ipykernel_411389/2551297254.py:7: SyntaxWarning: invalid escape sequence '\{'
  m = re.search("^\\\\text\{(?P<text>.+?)\}$", answer)


In [55]:
mathd_normalize_answer(model_answer)

'35 minutes'

In [56]:
mathd_normalize_answer(answer)

'Mark played for a total of 20 + 35 = <<20+35=55>>55 minutes.\nSo, he was on the sideline for 90 - 55 = <<90-55=35>>35 minutes.\n#### 35'

In [57]:
def extract_reference_answer(answer: str) -> str:
    match = ANS_RE.search(answer)
    if match:
        return match.group(1).strip().replace(",", "")
    return "[invalid]"

In [60]:
ANS_RE = re.compile(r"####\s*([\-0-9\.\,]+)")


In [61]:
extract_reference_answer(answer)

'35'

In [89]:
t1 = torch.randn(3,)

In [90]:
t1

tensor([-1.5766, -0.4595,  0.9613])

In [91]:
t2 = torch.randn(5)

In [92]:
t2

tensor([ 0.4149, -2.0955,  1.3975,  1.4119, -1.4094])

In [93]:
torch.cat([t1, t2], dim=0)

tensor([-1.5766, -0.4595,  0.9613,  0.4149, -2.0955,  1.3975,  1.4119, -1.4094])